version: '2'
services:
    api:
       build: .
       ports:
        - "3001:3001"
       env_file: .env
       links:
        - redis
        - mongo
        - postgres
    redis:
        image: redis:alpine
        ports:
         - "6379:6379"
    mongo:
        image: mongo:latest
        ports:
         - "27017:27017"
    postgres:
       image: postgres
       ports:
        - "5432:5432"
